### ISSUE TITLE
JSX bare attributes throw exception

### ISSUE THREAD

**Issue by remko** [zaach/jsxgettext#110]
When I run `jsxgettext` on the following JS(X) snippet:

```
const x = <input required/>;
```

I get an exception:

```
jsxgettext/lib/jsxgettext.js:29
    if (node.value.type === 'JSXExpressionContainer') {
                  ^

TypeError: Cannot read property 'type' of null
    at Object.assign.JSXAttribute (jsxgettext/lib/jsxgettext.js:29:19)
    at c (jsxgettext/node_modules/acorn/dist/walk.js:38:15)
```

Changing the bare attribute to `required={true}` fixes the error.

**Comment by BYK** [comment]
Fixed by #107.
